# Form implementation generated from reading ui file 'main-ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 10, 641, 361))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.get_label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.get_label.setFont(font)
        self.get_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.get_label.setWordWrap(False)
        self.get_label.setObjectName("get_label")
        self.verticalLayout.addWidget(self.get_label)
        self.get_list_view = QtWidgets.QListView(parent=self.widget)
        self.get_list_view.setObjectName("get_list_view")
        self.verticalLayout.addWidget(self.get_list_view)
        self.get_push_button = QtWidgets.QPushButton(parent=self.widget)
        self.get_push_button.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.get_push_button.setObjectName("get_push_button")
        self.verticalLayout.addWidget(self.get_push_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.post_label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.post_label.setFont(font)
        self.post_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.post_label.setWordWrap(False)
        self.post_label.setObjectName("post_label")
        self.verticalLayout_2.addWidget(self.post_label)
        self.post_list_view = QtWidgets.QListView(parent=self.widget)
        self.post_list_view.setObjectName("post_list_view")
        self.verticalLayout_2.addWidget(self.post_list_view)
        self.post_line_edit = QtWidgets.QLineEdit(parent=self.widget)
        self.post_line_edit.setMinimumSize(QtCore.QSize(0, 28))
        self.post_line_edit.setObjectName("post_line_edit")
        self.verticalLayout_2.addWidget(self.post_line_edit)
        self.post_button = QtWidgets.QPushButton(parent=self.widget)
        self.post_button.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.post_button.setObjectName("post_button")
        self.verticalLayout_2.addWidget(self.post_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mact test task"))
        self.get_label.setText(_translate("MainWindow", "GET request"))
        self.get_push_button.setText(_translate("MainWindow", "GET"))
        self.post_label.setText(_translate("MainWindow", "POST request"))
        self.post_line_edit.setPlaceholderText(
            _translate("MainWindow", "Введите текст...")
        )
        self.post_button.setText(_translate("MainWindow", "POST"))
