"""empty message

Revision ID: 1723acce13ed
Revises: 
Create Date: 2024-02-12 04:23:27.500410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1723acce13ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_and_count',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('local_time', sa.Time(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_time_added_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_and_count')
    # ### end Alembic commands ###
